name: Release
on:
    workflow_run:
        workflows: [Test]
        types:
            - completed

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.6

            - name: setup yarn
              run: |
                yarn set version stable
                yarn install

            - name: Release
              uses: cycjimmy/semantic-release-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
